spring:
  profiles:
    active: local
    include: API-KEY
  datasource:
    url: jdbc:h2:tcp://localhost/~/moai
    # url: jdbc:mysql://localhost:(MySQL? ????)/(DB??)?serverTimezone=Asia/Seoul
    username: sa
    password:
    driver-class-name: org.h2.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  messages:
    basename: i18n/exception
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

